### ISSUE TITLE
Bug: gap attribute in Stack component doesn't work

### ISSUE THREAD

**Issue by Zennisch** [kennex666/MusicSocialApp_ReactNative#11]
### Environment
- Operating System: Windows 11
- Node.js version: v20.17.0
- npm version: 10.8.3
- Other dependencies in package.json

### Steps to Reproduce
1. Create a simple Stack component:
```javascript
<Stack
  flexDirection="column"
  justifyContent="center"
  alignItems="center"
  gap={10}
>
  <Stack backgroundColor={"red"}><Text>Text 1</Text></Stack>
  <Stack backgroundColor={"green"}><Text>Text 2</Text></Stack>
  <Stack backgroundColor={"blue"}><Text>Text 3</Text></Stack>
</Stack>
```
2. Apply the component into a screen which should be seen after running the Expo app
(Example: `app/screens/TestingScreen/index.tsx`)
3. Run the app with: `npx expo start`
4. Check the result in Expo Go or browser

### Expected result
- Items in the main Stack component should have a gap of 10 units between them
- The gaps should be applied evenly between all child item

### Actual result
- There are no gaps between items
- Items are rendered adjacent to each other

**Comment by kennex666** [comment]
Hi @Zennisch,

Thanks for your report.

This is issue have been noticed and will be fixed soon.

Regards,

**Comment by kennex666** [comment]
Hi @Zennisch,

Good news! We've fixed the problem you reported.

Thanks for letting us know!
Best,
